name: Debug android 🎮
run-name: Debug android 🎮 ${{ github.ref }} ${{ github.sha }}

on: 
  workflow_dispatch:

env:
  UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

jobs:
  build:
    name: Debug for Android 🤖
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - "src/Office Worker"
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: false
          swap-storage: true
    
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cache
      - uses: actions/cache@v4
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build
      - uses: game-ci/unity-builder@v4
        with:
          versioning: Semantic
          projectPath: ${{ matrix.projectPath }}
          targetPlatform: Android
          androidExportType: androidPackage
          androidKeystoreName: user
          androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
          androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}
          androidTargetSdkVersion: AndroidApiLevel35
          buildName: OfficeWorker-debug-${{ github.run_number }}

      # Upload Build Artifact
      - uses: actions/upload-artifact@v4
        with:
          name: "Office-worker-development-${{ github.run_number }}"
          path: build

  notify:
    name: Notify via Telegram 📲
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: "Office-worker-development-${{ github.run_number }}"
          path: extracted_build

      - name: Extract APK
        run: |
          APK_FILE=$(find extracted_build -name "*.apk")
          echo "APK_FILE=$APK_FILE" >> $GITHUB_ENV

      - name: Send Telegram Notification with APK
        uses: appleboy/telegram-action@master
        with:
          token: ${{ secrets.TELEGRAM_TOKEN }}
          to: ${{ secrets.TELEGRAM_CI_CHAT_ID }}
          message: "New build for the Office Worker game is ready! Download the APK below."
          document: ${{ env.APK_FILE }}
